version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      backend:
        ipv4_address: 172.23.0.3
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  backend:
    build:
      context: ./ApiBackendYWebApp
    container_name: apibackendwebapp
    restart: always
    ports:
      - 8080:8080
    networks:
      backend:
        ipv4_address: 172.23.0.4

volumes:
  data: {}

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
