openapi: 3.0.0
info:
  version: 1.0.0
  title: Y platform WEB REST API
  description: The platform's API represents an interface to basic CRUD operations for Y platform.
servers:
  - url: https://7821f539-948c-4a01-b659-752d77cfc313.mock.pstmn.io
tags:
  - name: users
    description: Opertations on users data
  - name: posts
    description: Operations on posts data
  - name: comments
    description: Operations on comments data
paths:
  /users/{userId}:
    parameters:
      - name: userId
        description: The unique identifier of the user
        in: path
        required: true
        schema:
          type: integer
    summary: Find user by specifying userId.
    description: Use this endpoint to find a specific user.
    get:
      tags:          
          - users    
      description: Returns user data
      summary: Find users by ID
      operationId: getUserById
      deprecated: false
      responses:
        '200':
          description: Proper response for a userId request
          content:
            application/json:
              example:
                        id: 1
                        username: FirstNickForUser
                        description: A short description from users about themsleves 
                        email: fisr@user.com
                        age: 23
                        role: noAdmin
                        avatar_URL: https://some/endpoint.jpg
                        active: true
              schema:
                type: object
                required:
                  - id
                  - username
                  - email
                  - role
                  - active
                  - age
                properties:
                  id:
                    type: integer
                    description: UserId of a certain user
                  username:
                    type: string
                    description: Username of a user
                  description:
                    type: string
                    description: Description from a user
                  email:
                    type: string
                    format: email
                    description: The email address of the user
                  age:
                    type: integer
                    description: The age of the user
                  avatar_URL:
                    type: string
                    description: URL to source for user's avatar
                  role:
                    type: string
                    description: Role for authorization of a user
                  active:
                    type: boolean
                    description: Indicates if the user is active
        default:
          description: Error payload
          content:
            text/html:
              schema:
                type: string
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
    - ApiKey: []