application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: ywebapp
      port: 27017
      host: 172.23.0.3
      auto-index-creation: true